# usecase  Pandas

Data Cleaning
Data Analysis
Data Transformation
Data Visualization
Data Aggregation
Data File Handling
Data Filtering and Selection
Time Series And Analysis

# Pandas Series

a series is a one-dimensional labeled array capable of holding any data type. the axis 
lable are collectively called the index.
pip install pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
dic = {
    2:10,
    3:20,
    4:30
}

In [3]:
# list case series inlabel form in vertcal 
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
# custoum label
pd.Series(my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [5]:
# serige to array create in case 2-dimensional it gives error
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [6]:
# dectinary use it automatically 
pd.Series(dic)

2    10
3    20
4    30
dtype: int64

 in data science in multiple series so in case use data frame

# DataFrame

In [7]:
# create a data frame 
import numpy as np
import pandas as ps

# crate a dataframe

In [8]:
# using dictnary
data = {
    'name':['subhasish','mohit','dinesh','ram'],
    "age":[19,18,20,21],
    "city":["new york","paris","londomn","talcher"],
    "salary":[10000,21000,25000,18000]
}
df = pd.DataFrame(data)
print(df)

        name  age      city  salary
0  subhasish   19  new york   10000
1      mohit   18     paris   21000
2     dinesh   20   londomn   25000
3        ram   21   talcher   18000

In [9]:
data_list = [
    ['john',19,'london',65000],
    ['anna',34,'west bangol',48000],
    ['peter',28,'america',49000],
    ['linda',32,'paris',66000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1            2      3
0   john  19       london  65000
1   anna  34  west bangol  48000
2  peter  28      america  49000
3  linda  32        paris  66000

In [10]:
# using coumns using chane value
columns = ['Name','Age', 'City' ,'Salary']
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age         City  Salary
0   john   19       london   65000
1   anna   34  west bangol   48000
2  peter   28      america   49000
3  linda   32        paris   66000

# Selecting and Indexing Of Columns

In [11]:
df2

    Name  Age         City  Salary
0   john   19       london   65000
1   anna   34  west bangol   48000
2  peter   28      america   49000
3  linda   32        paris   66000

In [12]:
df2.columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [13]:
# selecting name columns
df2['Name']

0     john
1     anna
2    peter
3    linda
Name: Name, dtype: str

In [14]:
df2['City']

0         london
1    west bangol
2        america
3          paris
Name: City, dtype: str

In [15]:
# two columns selecting
df2[['Name','Salary']]

    Name  Salary
0   john   65000
1   anna   48000
2  peter   49000
3  linda   66000

In [16]:
# new columns create
df2["Designation"] = ['doctor','eng.','doctor','eng.']

In [17]:
df2

    Name  Age         City  Salary Designation
0   john   19       london   65000      doctor
1   anna   34  west bangol   48000        eng.
2  peter   28      america   49000      doctor
3  linda   32        paris   66000        eng.

In [18]:
# remove columns 
df2.drop('Designation', axis = 1)

    Name  Age         City  Salary
0   john   19       london   65000
1   anna   34  west bangol   48000
2  peter   28      america   49000
3  linda   32        paris   66000

In [19]:
df2

    Name  Age         City  Salary Designation
0   john   19       london   65000      doctor
1   anna   34  west bangol   48000        eng.
2  peter   28      america   49000      doctor
3  linda   32        paris   66000        eng.

In [20]:
# inplace using puri are ko remove
# in upper case drop only copy remove not main data
df2.drop('Designation', axis = 1, inplace = True)

In [21]:
df2

    Name  Age         City  Salary
0   john   19       london   65000
1   anna   34  west bangol   48000
2  peter   28      america   49000
3  linda   32        paris   66000

In [22]:
df2.drop('City', axis = 1)

    Name  Age  Salary
0   john   19   65000
1   anna   34   48000
2  peter   28   49000
3  linda   32   66000

In [23]:
df2

    Name  Age         City  Salary
0   john   19       london   65000
1   anna   34  west bangol   48000
2  peter   28      america   49000
3  linda   32        paris   66000

In [24]:
df2.drop('City', axis = 1, inplace = True)

In [25]:
df2

    Name  Age  Salary
0   john   19   65000
1   anna   34   48000
2  peter   28   49000
3  linda   32   66000

In [26]:
# row delete 
df2.drop(1, axis = 0, inplace = True)

In [27]:
df2

    Name  Age  Salary
0   john   19   65000
2  peter   28   49000
3  linda   32   66000

In [28]:
# acces rows
df2

    Name  Age  Salary
0   john   19   65000
2  peter   28   49000
3  linda   32   66000

In [29]:
# loc is use row selection
df2.loc[0]

Name       john
Age          19
Salary    65000
Name: 0, dtype: object

In [30]:
df2.loc[[0,2]]

    Name  Age  Salary
0   john   19   65000
2  peter   28   49000

In [31]:
# index location using iloc
df.iloc[3]

name          ram
age            21
city      talcher
salary      18000
Name: 3, dtype: object

# selecting subset of row and columns

In [32]:
df

        name  age      city  salary
0  subhasish   19  new york   10000
1      mohit   18     paris   21000
2     dinesh   20   londomn   25000
3        ram   21   talcher   18000

In [33]:
df.loc[[0,1]]

        name  age      city  salary
0  subhasish   19  new york   10000
1      mohit   18     paris   21000

In [34]:
df.loc[[0,2]][['name','salary']]

        name  salary
0  subhasish   10000
2     dinesh   25000

# condition Selection

In [35]:
df

        name  age      city  salary
0  subhasish   19  new york   10000
1      mohit   18     paris   21000
2     dinesh   20   londomn   25000
3        ram   21   talcher   18000

In [36]:
# age above and equal 20 
df[df["age"] >= 20]

     name  age     city  salary
2  dinesh   20  londomn   25000
3     ram   21  talcher   18000

In [37]:
# only want people which age equal and above 20 and city must be talcher
df[(df['age']>= 20) & (df['city'] == 'talcher')]

  name  age     city  salary
3  ram   21  talcher   18000

# Missing data

finding missing data 
removing missing data
filling the missing data

In [38]:
import numpy as np
import pandas as ps

In [64]:
# find missing data  ->np.nan is non value
data_list = [
    ['john',19,np.nan,65000],
    ['ram',34,'west bangol',48000],
    ['peter',28,np.nan,np.nan],
    ['linda',np.nan,np.nan,66000]
]
df = pd.DataFrame(data_list)

In [65]:
df

       0     1            2        3
0   john  19.0          NaN  65000.0
1    ram  34.0  west bangol  48000.0
2  peter  28.0          NaN      NaN
3  linda   NaN          NaN  66000.0

In [66]:
# check non value
df.isnull()

       0      1      2      3
0  False  False   True  False
1  False  False  False  False
2  False  False   True   True
3  False   True   True  False

In [67]:
df.isna()

       0      1      2      3
0  False  False   True  False
1  False  False  False  False
2  False  False   True   True
3  False   True   True  False

In [68]:
# each colum 
df.isnull().sum()
# df.isna().sum()

0    0
1    1
2    3
3    1
dtype: int64

In [69]:
# identyfa 
df.isnull().any()

0    False
1     True
2     True
3     True
dtype: bool

In [70]:
df

       0     1            2        3
0   john  19.0          NaN  65000.0
1    ram  34.0  west bangol  48000.0
2  peter  28.0          NaN      NaN
3  linda   NaN          NaN  66000.0

In [71]:
# removing missing data 
# it work rowbased it deleate row that missing value it on 
df.dropna()

     0     1            2        3
1  ram  34.0  west bangol  48000.0

In [72]:
df

       0     1            2        3
0   john  19.0          NaN  65000.0
1    ram  34.0  west bangol  48000.0
2  peter  28.0          NaN      NaN
3  linda   NaN          NaN  66000.0

In [76]:
# thresh is use to in case check 3 non-null value
# atleat 3 non value nhi hona chiya
df.dropna(thresh = 3)

      0     1            2        3
0  john  19.0          NaN  65000.0
1   ram  34.0  west bangol  48000.0

In [77]:
# filling missing data
# non value is 0   -> inplace = True then main data affected
df.fillna(0)

       0     1            2        3
0   john  19.0            0  65000.0
1    ram  34.0  west bangol  48000.0
2  peter  28.0            0      0.0
3  linda   0.0            0  66000.0

In [78]:
# different values  -> column wise
values = {
    1:"shayam",
    2: 22,
    3:"asiya",
    4:46000
}
df.fillna(value = values)

       0       1            2        3
0   john    19.0           22  65000.0
1    ram    34.0  west bangol  48000.0
2  peter    28.0           22    asiya
3  linda  shayam           22  66000.0

# Merging , joining and concatination

merging two dataframe

In [81]:
import numpy as np
import pandas as pd

In [82]:
employees = pd.DataFrame({
    "employe_id":[1,2,3,4,5],
    "name":['john','rahul','lina','bob','peter'],
    "department":['HR','IT','FINANCE','IT','HR']
})

salaries = pd.DataFrame({
    'employe_id':[1,2,3,6,7],
    'salary':[60000,49000,66000,56000,90000],
    'bonus':[5000,10000,7000,5000,12000]
})

In [83]:
employees

   employe_id   name department
0           1   john         HR
1           2  rahul         IT
2           3   lina    FINANCE
3           4    bob         IT
4           5  peter         HR

In [84]:
salaries

   employe_id  salary  bonus
0           1   60000   5000
1           2   49000  10000
2           3   66000   7000
3           6   56000   5000
4           7   90000  12000

In [85]:
# common 1,2,3 i see that
# mearging  ->only common give 
pd.merge(employees,salaries)

   employe_id   name department  salary  bonus
0           1   john         HR   60000   5000
1           2  rahul         IT   49000  10000
2           3   lina    FINANCE   66000   7000

In [89]:
# how = default -> inner, 'outer' -> all data missing value nan
pd.merge(employees,salaries, on ='employe_id', how = 'inner')

   employe_id   name department  salary  bonus
0           1   john         HR   60000   5000
1           2  rahul         IT   49000  10000
2           3   lina    FINANCE   66000   7000

In [90]:
# all are but not that nan value
pd.merge(employees,salaries, on ='employe_id', how = 'outer')

   employe_id   name department   salary    bonus
0           1   john         HR  60000.0   5000.0
1           2  rahul         IT  49000.0  10000.0
2           3   lina    FINANCE  66000.0   7000.0
3           4    bob         IT      NaN      NaN
4           5  peter         HR      NaN      NaN
5           6    NaN        NaN  56000.0   5000.0
6           7    NaN        NaN  90000.0  12000.0

In [93]:
# employe_id  left all id shown in 1st data frame 
pd.merge(employees,salaries, on ='employe_id', how = 'left')

   employe_id   name department   salary    bonus
0           1   john         HR  60000.0   5000.0
1           2  rahul         IT  49000.0  10000.0
2           3   lina    FINANCE  66000.0   7000.0
3           4    bob         IT      NaN      NaN
4           5  peter         HR      NaN      NaN

In [94]:
# right means second data all are present with common and fill nan
pd.merge(employees,salaries, on ='employe_id', how = 'right')

   employe_id   name department  salary  bonus
0           1   john         HR   60000   5000
1           2  rahul         IT   49000  10000
2           3   lina    FINANCE   66000   7000
3           6    NaN        NaN   56000   5000
4           7    NaN        NaN   90000  12000

# Concatination two dataframe

In [95]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B3'],
    'C':['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [96]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B3  C2

In [97]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [98]:
# apply concatination adding a new line data frame df2
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B3  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [100]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B3  C2

In [101]:
# row basis
pd.concat([df1,df2], axis =1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B3  C2  A5  B5  C5

# row and coloumns addin use concatination
# one colums using mearge

# joining to two Dataframe

In [103]:
df1 = pd.DataFrame({
    'name': ['alice','bob','charline'],
}, index = [1,2,3])
# second dataframe
df2 = pd.DataFrame({
    'score':[85,98,75]
}, index = [2,3,4])

In [104]:
df1

       name
1     alice
2       bob
3  charline

In [105]:
df2

   score
2     85
3     98
4     75

In [106]:
# join data 1 and data2
df1.join(df2)

       name  score
1     alice    NaN
2       bob   85.0
3  charline   98.0

In [107]:
df1.join(df2, how = 'outer')

       name  score
1     alice    NaN
2       bob   85.0
3  charline   98.0
4       NaN   75.0

# Groupby and Aggregation

In [114]:
import numpy as np
import pandas as pd

In [120]:
data = {
    'categort':['A','B','A','B','A','B','A','B'],
    'store': ['51','51','52','52','51','52','52','51'],
    'sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'data':pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  categort store  sales  Quantity       data
0        A    51    100        10 2023-01-01
1        B    51    200        15 2023-01-02
2        A    52    150        12 2023-01-03
3        B    52    250        18 2023-01-04
4        A    51    120         8 2023-01-05
5        B    52    180        20 2023-01-06
6        A    52    200        15 2023-01-07
7        B    51    300        25 2023-01-08

In [121]:
# group by category and calculate the sum of sales using gropby
cat = df.groupby('categort')
for i, v in cat :
    print(i)
    print(v)

A
  categort store  sales  Quantity       data
0        A    51    100        10 2023-01-01
2        A    52    150        12 2023-01-03
4        A    51    120         8 2023-01-05
6        A    52    200        15 2023-01-07
B
  categort store  sales  Quantity       data
1        B    51    200        15 2023-01-02
3        B    52    250        18 2023-01-04
5        B    52    180        20 2023-01-06
7        B    51    300        25 2023-01-08

In [122]:
cat = df.groupby('categort')['sales'].sum()
cat

categort
A    570
B    930
Name: sales, dtype: int64

In [123]:
# groupby store and calculate the sum of sales 
cat1 = df.groupby('store')['sales'].sum()
cat1

store
51    720
52    780
Name: sales, dtype: int64

In [124]:
# group by multiple columns
# group by category and store
cat2 = df.groupby(['categort','store'])['sales'].sum()
cat2

categort  store
A         51       220
          52       350
B         51       500
          52       430
Name: sales, dtype: int64

# Aggregation

In [127]:
# it is multiple things combinen fine mean ,mode,standdavition etc
df['sales'].mean()

np.float64(187.5)

 mean, median,minimum, maximum, count,std etc

In [130]:
df['sales'].agg(['mean','min','max','sum','count','std','median'])

mean       187.500000
min        100.000000
max        300.000000
sum       1500.000000
count        8.000000
std         66.062741
median     190.000000
Name: sales, dtype: float64

# Pivot Tables